[package]
name = "rash"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cranelift = "0.113.0"
target-lexicon = "0.12.16"
memmap2 = "0.9.5"
lazy_static = "1.5.0"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
zip-extract = "0.2.1"
tempfile = "3.13.0"
