[package]
name = "rash"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rash_vm = { path = "../rash_vm" }
rash_loader_sb3 = { path = "../rash_loader_sb3" }
