[package]
name = "rash_render"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.29"
env_logger = "0.10"
log = "0.4"
wgpu = "22.0"
bytemuck = { version = "1.20.0", features = ["derive"] }
