[package]
name = "rash_loader_sb3"
version = "0.1.0"
edition = "2024"

[dependencies]
rash_core.path = "../rash_core"
rash_vm.path = "../rash_vm"
rash_loader_sb3_json.path = "../rash_loader_sb3_json"

serde_json.workspace = true
zip = { version = "8.*", default-features = false, features = ["deflate"] }
